branch-defaults:
  default:
    environment: udagram-api-dev
environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram-api
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2/5.5.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
