version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run install:frontend
      - run:
          name: Back-End Install
          command: |
            npm run install:backend
      - run:
          name: Front-End Build
          command: |
            npm run build:frontend
      - run:
          name: Back-End Build
          command: |
            npm run build:backend
      - run:
          name: Front-End Deploy
          command: |
            npm run deploy:frontend
      - run:
          name: Back-End Deploy
          command: |
            npm run deploy:backend
