version: 2.1
orbs:
  node: circleci/node@4.1.0
  angular: okode/angular@2.0.13
  # aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run install:frontend
      - run:
          name: Back-End Install
          command: |
            npm run install:backend
      - run:
          name: Front-End Build
          command: |
            npm run build:frontend
      - run:
          name: Back-End Build
          command: |
            npm run build:backend